cmake_minimum_required(VERSION 3.18)
project(nomad LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2")
set(GLUE ${CMAKE_ANDROID_NDK}/sources/android/native_app_glue)
add_library(glue STATIC ${GLUE}/android_native_app_glue.c)
target_include_directories(glue PUBLIC ${GLUE})
add_library(nomad SHARED main.cpp)
target_link_libraries(nomad glue android EGL GLESv3 log)
set_target_properties(nomad PROPERTIES LINK_FLAGS "-u ANativeActivity_onCreate")
